// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-TyZqwm6rXk7MEQyYv-4rD1UnUiQXjo',
    appId: '1:714363337344:web:2f6cacd594217ea29ec465',
    messagingSenderId: '714363337344',
    projectId: 'adib-pharmacy',
    authDomain: 'adib-pharmacy.firebaseapp.com',
    storageBucket: 'adib-pharmacy.firebasestorage.app',
    measurementId: 'G-SFVTK1X6YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5SU3AzQlCTov_XCGnjYjMAQew1jroDCs',
    appId: '1:714363337344:android:6777f0258ee41fe89ec465',
    messagingSenderId: '714363337344',
    projectId: 'adib-pharmacy',
    storageBucket: 'adib-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNSXL7tjOLM03_rROWU_XHcgawC7aspm8',
    appId: '1:714363337344:ios:1c833700ddba61a19ec465',
    messagingSenderId: '714363337344',
    projectId: 'adib-pharmacy',
    storageBucket: 'adib-pharmacy.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNSXL7tjOLM03_rROWU_XHcgawC7aspm8',
    appId: '1:714363337344:ios:1c833700ddba61a19ec465',
    messagingSenderId: '714363337344',
    projectId: 'adib-pharmacy',
    storageBucket: 'adib-pharmacy.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8-TyZqwm6rXk7MEQyYv-4rD1UnUiQXjo',
    appId: '1:714363337344:web:6c7b99e5aa3280479ec465',
    messagingSenderId: '714363337344',
    projectId: 'adib-pharmacy',
    authDomain: 'adib-pharmacy.firebaseapp.com',
    storageBucket: 'adib-pharmacy.firebasestorage.app',
    measurementId: 'G-KTTE0TRPVP',
  );
}
